### ISSUE TITLE
Request for new top-level namespace for Fortify

### ISSUE THREAD

**Issue by dylanbthomas** [CycloneDX/cyclonedx-property-taxonomy#33]
Fortify has introduced support to produce and import CycloneDX SBOMs, and CycloneDX will feature as our primary/preferred SBOM standard moving forward.  We anticipate future enhancements to our output SBOMs that may have Fortify-specific properties and would like to request a reserved 'fortify' namespace in preparation for future development.

**Comment by stevespringett** [comment]
Excellent. Thanks for the info. As a long-time and current Fortify user (since v2.50), I'm thrilled that Fortify is standardizing on CycloneDX. The `fortify` namespace has been reserved. Please let us know when the namespace has been publicly defined and the URL to the documentation so we can update the docs on our end.

**Comment by jkowalleck** [comment]
@dylanbthomas ,

the Top-Level namespace `fortify` was registered a while ago. Could you add the respective taxonomy documentation?
